@url = http://localhost:{{$dotenv PORT}}
# @url = http://localhost:3000

@mainEndpoint = companies/addfavorites
@idcompany = 1
### POST /companies/addfavorites/:idcompany
POST {{url}}/{{mainEndpoint}}/{{idcompany}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJpYXQiOjE3NTQ0MzU4MjcsImV4cCI6MTc1NDQzOTQyN30.ipZhV-wif8HNy8wl52jYUoYCmg6GoZlqE1XjD765afo
Content-Type: application/json

